### ISSUE TITLE
When requesting to show multiple notifications, not all of them show

### ISSUE THREAD

**Issue by hyperh** [minhtranite/react-notifications#19]
Sometimes when I want to show multiple notifications within a short time period, not all of them show up. This is because the key is generated with a timestamp. This should be done using a `uuid`.

https://github.com/minhtranite/react-notifications/blob/master/src/NotificationManager.js#L25

**Comment by LiranBri** [comment]
As a quick workaround until this would get resolved, you can use setTimeout with minor milliseconds between each call
