### ISSUE TITLE
Callback function not firing

### ISSUE THREAD

**Issue by cell2749** [minhtranite/react-notifications#21]
Notification is displayed, however the Hello World is not written to the console, thus I assume the callback is not fired.
`NotificationManager.error("Msg", "Title", 3000, ()=>{
                        console.log("Hello World");
                    });
`

**Comment by cell2749** [comment]
Nevermind, realised what the callback was for. The issue can be closed

**Comment by AlexandrDobrovolskiy** [comment]
same issue
