### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by fabiopaiva-innovactory** [minhtranite/react-notifications#23]
Please, add on instructions to install `react-addons-css-transition-group`

    npm install react-addons-css-transition-group --save

**Comment by nikegp** [comment]
Actually it's deprecated so would be great to replace it with a newer one https://www.npmjs.com/package/react-addons-css-transition-group

**Comment by minhtranite** [comment]
Now, we use `react-transition-group` https://github.com/minhtranite/react-notifications/blob/master/package.json#L21
